import { runPython, spawnSandboxed, sandboxCaps } from "../src/sandbox/runner.js";
console.log(sandboxCaps());
const rows = Array.from({ length: 10 }, (_, i) => ({ year: 2015 + i, asr: 5 + i * 0.3 }));
const t = Date.now();
let r = await runPython({ code: "plt.plot(df.year, df.asr); plt.title('x'); print(df.shape)", columns: ["year", "asr"], rows });
console.log("png", r.ok, r.files, r.stdout.trim(), r.error, Date.now() - t, "ms");
r = await runPython({ code: "import socket\nprint('imported')", columns: [], rows: [] });
console.log("socket", r.ok, r.error);
r = await runPython({ code: "print(open('/etc/passwd').read()[:50])", columns: [], rows: [] });
console.log("passwd", r.ok, r.error);
r = await runPython({ code: "import subprocess\nsubprocess.run(['ls'])", columns: [], rows: [] });
console.log("subprocess", r.ok, r.error);
r = await runPython({ code: "import os\nos.system('ls')", columns: [], rows: [] });
console.log("os.system", r.ok, r.error);
r = await runPython({ code: "import urllib.request\nurllib.request.urlopen('https://example.com')", columns: [], rows: [] });
console.log("urllib", r.ok, r.error);
r = await runPython({ code: "import plotly.express as px\nfig = px.line(df, x='year', y='asr')", columns: ["year", "asr"], rows });
console.log("plotly", r.ok, r.files, r.error);
r = await runPython({ code: "while True: pass", columns: [], rows: [], timeoutS: 4 });
console.log("loop", r.ok, r.timed_out, r.error, r.duration_ms);
const n = await spawnSandboxed(["/usr/bin/python3", "-c", "import socket; s=socket.create_connection(('1.1.1.1', 443), 3); print('CONNECTED')"], { cwd: "/tmp", timeoutS: 10 });
console.log("raw net", n.code, n.stdout.trim(), n.stderr.trim().split("\n").at(-1));
