import { ALL_TOOLS, modelSafe } from "../src/tools/index.js";
import { newToolCtx } from "../src/tools/types.js";
import { SERVE } from "../src/db/duck.js";
const fac = (await SERVE().rows(`SELECT f.facility_id, count(DISTINCT a.alert_id) FILTER (WHERE a.severity='HIGH') h FROM pt_patient_facility f LEFT JOIN pt_alerts a ON a.patient_id=f.patient_id GROUP BY 1 ORDER BY h DESC LIMIT 3`));
console.log(fac);
const m = newToolCtx({ role: "ministry", facilityId: null });
const d = newToolCtx({ role: "doctor", facilityId: Number(fac[0].facility_id) });
const by = Object.fromEntries(ALL_TOOLS.map((t) => [t.name, t]));
const run = async (name: string, inp: any, t: any) => { const o = await by[name].execute(by[name].inputSchema.parse(inp), t); const s = JSON.stringify(modelSafe(by[name], o, t)); console.log(`\n## ${name}`, s.length, s.slice(0, 600)); return o; };
await run("get_kpis", {}, m);
await run("get_rates_trend", { age_band: "<50", year_from: 2015 }, m);
await run("get_district_ranking", { top: 5 }, m);
await run("get_care_cascade", {}, m);
await run("get_stage_mix", { by: "tier" }, m);
await run("get_survival", { include_curve: true, include_cox: true }, m);
await run("get_facility_quality", {}, m);
await run("get_model_metrics", { include_subgroups: true }, m);
await run("query_marts", { sql: "SELECT geo_code, period, cases, asr FROM mart_rates WHERE level='DISTRICT' AND period_type='YEAR' AND sex='ALL' AND age_band='<50' ORDER BY cases LIMIT 5" }, m);
await run("query_marts", { sql: "SELECT given_name FROM pt_patient" }, m);
await run("describe_tables", {}, m);
const l = await run("list_high_risk_patients", {}, d) as any;
await run("list_alerts", {}, d);
const pid = l.rows[0].patient_id;
await run("get_patient", { patient_id: pid }, d);
await run("get_patient_timeline", { patient_id: pid }, d);
await run("get_patient_risk", { patient_id: pid }, d);
const w = await run("make_patient_widget", { patient_id: pid }, d) as any;
console.log("UI widget name:", w.name, "events:", w.timeline?.events.length, "labs:", w.labs?.length, w.suggested_actions);
await run("query_marts", { sql: "SELECT p.display_id, r.risk_band, r.ensemble_prob FROM pt_risk r JOIN pt_patient p USING (patient_id) ORDER BY r.ensemble_prob DESC LIMIT 5" }, d);
await run("query_marts", { sql: "SELECT given_name FROM pt_patient LIMIT 3" }, d);
const ds = m.datasets.ids()[1];
await run("make_chart", { type: "line", title: "Under-50 ASR", dataset_id: ds, x: "year", series: [{ key: "asr", lci: "asr_lci", uci: "asr_uci" }] }, m);
await run("make_chart", { type: "line", title: "bad", dataset_id: ds, x: "yr", y: "asr" }, m);
