import { type ReactNode, useEffect, useState } from "react";
import { useLocation, useNavigate } from "react-router-dom";
import { Badge, Button, Chip, Dropdown, DropdownItem, DropdownMenu, DropdownSection, DropdownTrigger, Kbd, Tooltip } from "@heroui/react";
import { AnimatePresence, motion } from "framer-motion";
import { Bell, Building2, Check, ChevronDown, Database, Landmark, Moon, Search, Stethoscope, Sun } from "lucide-react";
import { useStatus } from "@/api/hooks";
import { InfoHint } from "@/components/ui/InfoHint";
import { PillTabs } from "@/components/ui/PillTabs";
import { ago, date } from "@/lib/format";
import { useTheme } from "@/lib/theme";
import { useLive } from "@/state/live";
import { useRole } from "@/state/role";
import { useInsightsUi, useRouteInsights } from "./InsightsFab";
import { activeNav, navFor } from "./nav";

const iconBtn = "min-w-9 w-9 h-9 bg-surface border border-border shadow-tile text-fg-muted data-[hover=true]:text-fg data-[hover=true]:bg-surface-2";

export function Logo() {
  return (
    <div className="flex items-center gap-2.5 shrink-0">
      <span className="w-9 h-9 rounded-[12px] bg-cta-gradient grid place-items-center shadow-[0_8px_18px_-8px_rgb(var(--accent)/0.8)]" aria-hidden>
        <svg viewBox="0 0 32 32" className="w-6 h-6"><path d="M3 23 L10.5 12.5 L15 18 L21 8 L29 23" fill="none" stroke="white" strokeWidth="2.4" strokeLinejoin="round" strokeLinecap="round" /><circle cx="21" cy="8" r="2.6" fill="white" /></svg>
      </span>
      <div className="leading-tight">
        <div className="font-semibold tracking-tight text-[16px] text-fg">Early Signals</div>
        <div className="text-micro text-fg-muted">Gastric cancer · Rwanda</div>
      </div>
    </div>
  );
}

function SyntheticNote() {
  return (
    <div role="note" aria-label="Synthetic data notice" className="hidden lg:flex items-center">
      <Chip size="sm" radius="full" variant="flat" classNames={{ base: "bg-warning/15 h-6", content: "text-[11px] font-medium text-tone-warning px-1" }}>Synthetic data</Chip>
      <InfoHint size={13} label="About the synthetic data" content={<><b>Synthetic data for demonstration</b> — not real patients or real district statistics. The EMR records are generated by an OpenMRS-shaped simulator.</>} />
    </div>
  );
}

function LiveIndicator() {
  const { data } = useStatus();
  const live = useLive();
  const [, tick] = useState(0);
  useEffect(() => { const t = setInterval(() => tick((x) => x + 1), 30_000); return () => clearInterval(t); }, []);
  const run = data?.data?.pipeline;
  const sim = live.simTime ?? data?.meta?.sim_time;
  const published = live.lastRefresh ?? (data?.meta?.published_at ? Date.parse(data.meta.published_at) : null);
  const stale = published ? Date.now() - published > 2 * 5 * 60_000 && !live.lastRefresh : false;
  const failed = run?.status === "FAILED";
  const dot = failed ? "bg-danger" : stale ? "bg-warning" : "bg-success";
  return (
    <Tooltip placement="bottom" delay={150} classNames={{ content: "bg-surface text-fg border border-border shadow-float rounded-tile px-3 py-2" }}
             content={
               <dl className="text-xs grid grid-cols-[auto_auto] gap-x-3 gap-y-1 tabular">
                 <dt className="text-fg-muted">Last refresh</dt><dd>{ago(published)}</dd>
                 <dt className="text-fg-muted">Simulated date</dt><dd>{date(sim)}</dd>
                 <dt className="text-fg-muted">Pipeline run</dt><dd>#{live.runId ?? data?.meta?.run_id ?? "—"}{failed ? " · last run failed" : ""}</dd>
                 <dt className="text-fg-muted">Live updates</dt><dd>{live.connected ? "connected" : "polling"}</dd>
               </dl>
             }>
      <button type="button" className="hidden xl:flex items-center gap-2 h-9 px-3 rounded-full text-xs text-fg-muted hover:text-fg hover:bg-fg/5 tabular focus:outline-none focus-visible:ring-2 focus-visible:ring-accent/60"
              aria-label={`Data updated ${ago(published)}${failed ? ", last run failed" : ""}`}>
        <span className="relative flex w-2 h-2" aria-hidden>
          {!stale && !failed && <span className={`absolute inset-0 rounded-full ${dot} animate-ping2`} />}
          <span className={`relative w-2 h-2 rounded-full ${dot}`} />
        </span>
        <span aria-live="polite" className="whitespace-nowrap">Updated {ago(published)}</span>
      </button>
    </Tooltip>
  );
}

function ThemeToggle() {
  const { theme, toggle } = useTheme();
  return (
    <Button isIconOnly size="sm" radius="full" variant="flat" className={iconBtn} aria-label="Toggle light/dark theme" onPress={toggle}>
      <AnimatePresence mode="wait" initial={false}>
        <motion.span key={theme} initial={{ rotate: -90, opacity: 0, scale: 0.6 }} animate={{ rotate: 0, opacity: 1, scale: 1 }} exit={{ rotate: 90, opacity: 0, scale: 0.6 }} transition={{ duration: 0.2 }} className="grid place-items-center">
          {theme === "dark" ? <Sun size={16} aria-hidden /> : <Moon size={16} aria-hidden />}
        </motion.span>
      </AnimatePresence>
    </Button>
  );
}

function RoleMenu() {
  const { role, setRole, facilityName } = useRole();
  const navigate = useNavigate();
  const fac = facilityName?.replace(" (Synthetic)", "") ?? null;
  const label = role === "doctor" ? `Doctor${fac ? ` · ${fac}` : ""}` : "Ministry";
  return (
    <Dropdown placement="bottom-end" classNames={{ content: "bg-surface border border-border shadow-float rounded-tile min-w-[260px]" }}>
      <DropdownTrigger>
        <Button size="sm" radius="full" variant="flat" className="h-9 pl-1 pr-3 min-w-[120px] max-w-[280px] shrink-0 bg-surface border border-border shadow-tile text-fg data-[hover=true]:bg-surface-2"
                startContent={<span className="w-7 h-7 rounded-full bg-accent-soft text-accent grid place-items-center shrink-0" aria-hidden>{role === "doctor" ? <Stethoscope size={14} /> : <Landmark size={14} />}</span>}
                endContent={<ChevronDown size={14} className="text-fg-muted shrink-0" aria-hidden />}>
          <span className="truncate text-[13px] font-medium">{label}</span>
        </Button>
      </DropdownTrigger>
      <DropdownMenu aria-label="Switch role" onAction={(k) => {
        if (k === "ministry") { setRole("ministry"); navigate("/"); }
        if (k === "doctor") { setRole("doctor"); navigate("/doctor"); }
      }}>
        <DropdownSection title="View as" classNames={{ heading: "text-micro text-fg-muted px-2" }}>
          <DropdownItem key="ministry" description="Aggregates only, small cells suppressed" startContent={<Landmark size={16} className="text-accent" aria-hidden />}
                        endContent={role === "ministry" ? <Check size={15} className="text-accent" aria-hidden /> : null}>Ministry</DropdownItem>
          <DropdownItem key="doctor" description={fac ? `Patient-level data · ${fac}` : "Patient-level data for one facility"} startContent={<Building2 size={16} className="text-accent" aria-hidden />}
                        endContent={role === "doctor" ? <Check size={15} className="text-accent" aria-hidden /> : null}>Doctor</DropdownItem>
        </DropdownSection>
      </DropdownMenu>
    </Dropdown>
  );
}

/** Top navigation (plan §A3): logo, centred navy pill tabs by role, live indicator and icon actions, role pill. */
export function TopNav({ onCmd, onDq, extra }: { onCmd: () => void; onDq: () => void; extra?: ReactNode }) {
  const role = useRole((s) => s.role);
  const { pathname } = useLocation();
  const items = navFor(role);
  const current = activeNav(pathname);
  const sel = current && items.some((i) => i.to === current.to) ? current.to : "";
  const { cards } = useRouteInsights();
  const setInsights = useInsightsUi((s) => s.setOpen);
  const n = cards.length;
  return (
    <header className="h-16 shrink-0 flex items-center gap-4 px-5">
      <div className="flex items-center gap-3 shrink-0">
        <Logo />
        <SyntheticNote />
      </div>
      <nav aria-label="Primary" className="flex-1 min-w-0 flex justify-center">
        <PillTabs variant="navy" ariaLabel="Views" selectedKey={sel} size="md"
                  items={items.map((i) => ({ key: i.to, href: i.to, label: i.label, icon: <i.icon size={14} className="hidden min-[1700px]:block" aria-hidden /> }))} />
      </nav>
      <div className="flex items-center gap-2 shrink-0">
        <LiveIndicator />
        {extra}
        <Tooltip content={<span className="flex items-center gap-1.5 text-xs">Search <Kbd keys={["ctrl"]}>K</Kbd></span>} delay={300} placement="bottom">
          <Button isIconOnly size="sm" radius="full" variant="flat" className={iconBtn} aria-label="Search" aria-keyshortcuts="Control+K" onPress={onCmd}><Search size={16} aria-hidden /></Button>
        </Tooltip>
        <Tooltip content="Data quality" delay={300} placement="bottom">
          <Button isIconOnly size="sm" radius="full" variant="flat" className={iconBtn} aria-label="Data quality" onPress={onDq}><Database size={16} aria-hidden /></Button>
        </Tooltip>
        <Badge content={n} isInvisible={!n} color="primary" size="sm" shape="circle" placement="top-right" classNames={{ badge: "border-surface text-[10px] font-semibold" }}>
          <Button isIconOnly size="sm" radius="full" variant="flat" className={iconBtn} aria-label={n ? `AI insights, ${n} new` : "AI insights, none for this view"} isDisabled={!n} onPress={() => setInsights(true)}>
            <Bell size={16} aria-hidden />
          </Button>
        </Badge>
        <ThemeToggle />
        <RoleMenu />
      </div>
    </header>
  );
}
