import { http, HttpResponse } from "msw";
import { useRole } from "@/state/role";
import fixtures from "./fixtures.json";

/** Mock API for VITE_USE_MOCKS=true (SPEC §16.6): replays responses recorded from a full UI walk-through
 *  (scripts/record-mocks.mjs, `npm run mocks:record`). Exact URL first, then the same path with any query, so unseen filter combinations still
 *  render plausible data. Writes (alert status, notes) are echoed back. */
type Rec = { status: number; body: unknown };
const GET = (fixtures as { get: Record<string, Rec> }).get;
const ASK = (fixtures as { ask: Record<string, unknown> }).ask;
const byPath = new Map<string, Rec>();
for (const [k, v] of Object.entries(GET)) {
  const path = k.split("?")[0];
  if (!byPath.has(path) || v.status === 200) byPath.set(path, v);
}

function lookup(url: URL): Rec | undefined {
  const role = useRole.getState().role;
  const key = `${role}${url.pathname}${url.search}`;
  if (GET[key]) return GET[key];
  const exactPath = byPath.get(`${role}${url.pathname}`);
  if (exactPath) return exactPath;
  // patient-specific paths fall back to any recorded patient of the same shape (/patients/{id}/case, ...)
  const generic = url.pathname.replace(/\/patients\/\d+/, "/patients/");
  for (const [k, v] of byPath) if (k.startsWith(role) && k.slice(role.length).replace(/\/patients\/\d+/, "/patients/") === generic) return v;
  return undefined;
}

export const handlers = [
  http.get("/api/v1/*", ({ request }) => {
    const rec = lookup(new URL(request.url));
    if (!rec) return HttpResponse.json({ error: { code: "NOT_RECORDED", message: "No mock recorded for this request", details: {} } }, { status: 404 });
    return HttpResponse.json(rec.body as Record<string, unknown>, { status: rec.status });
  }),
  http.post("/api/v1/ask", async ({ request }) => {
    const { question } = (await request.json()) as { question: string };
    const hit = ASK[question] ?? Object.values(ASK)[0];
    return HttpResponse.json(hit as Record<string, unknown>);
  }),
  http.patch("/api/v1/alerts/:id", async ({ request, params }) => {
    const body = (await request.json()) as Record<string, unknown>;
    return HttpResponse.json({ meta: {}, data: { alert_id: params.id, ...body } });
  }),
  http.post("/api/v1/patients/:id/explain", () => HttpResponse.json({ meta: {}, data: {
    summary: "Mock mode: the explanation is generated by the API from this patient's risk reasons and timeline.",
    disclaimer: "Decision support only - synthetic data.", generated_by: "mock" } })),
  http.post("/api/v1/patients/:id/notes", async ({ request }) => {
    const body = (await request.json()) as { note: string };
    return HttpResponse.json({ meta: {}, data: { note: body.note, created_at: new Date().toISOString() } });
  }),
];
